name: ecv2
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - opencv=4.2.0
  - pillow
  - python=3.8.1
  - pytorch=1.4.0
  - torchvision=0.5.0
  - magma-cuda101=2.5.1
  - tqdm=4.42.1
  - pycocotools
  - pycrypto=2.6.1
  - pbkdf2=1.3
  - distro=1.5.0
  - paramiko
  - pip
  - pip:
    - salt==3001
